'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Other
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Study_Room.Other", GetType(Other).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property apple_with_worm_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apple_with_worm_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property balloon_deflated_35ce5c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balloon_deflated_35ce5c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property bone_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bone_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property brick_hole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_hole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property brick_side_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_side_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property candy_small_35ce5c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("candy_small_35ce5c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property card_35ce5c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card_35ce5c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property card_reader_00ff00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card_reader_00ff00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property card_reader_ff0000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card_reader_ff0000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_digital_1_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_digital_1_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_digital_3_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_digital_3_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_digital_5_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_digital_5_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_1_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_1_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_2_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_2_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_3_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_3_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_3_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_3_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_4_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_4_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_5_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_5_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_6_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_6_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_7_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_7_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_7_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_7_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_number_marker_9_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_number_marker_9_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_symbol_marker_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_symbol_marker_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_symbol_marker_multiple_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_symbol_marker_multiple_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_symbol_marker_percent_ffffff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_symbol_marker_percent_ffffff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property char_symbol_marker_question_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("char_symbol_marker_question_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cheese_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheese_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property coin_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property elite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property favicon_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mobile_phone_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mobile_phone_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mobile_phone_v_call() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mobile_phone_v_call", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mobile_phone_v_lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mobile_phone_v_lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mug_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mug_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property paper_crumpled_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paper_crumpled_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property room_escape_maker_logo_60_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("room_escape_maker_logo_60_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property screw_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screw_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property slotted_screw_fastened_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slotted_screw_fastened_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property table_side_764928() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_side_764928", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property whiteboard_eraser_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("whiteboard_eraser_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
